# Build source distribution
task:
  name: "Build sdist for unsupported platforms"
  
  container:
    image: python:3.8

  install_script:
    - python setup.py sdist

  script:
    - python3 -m pip install -U --force-reinstall --no-index --find-links=./dist pysdl2-dll
    - python3 -m pip install pytest git+https://github.com/marcusva/py-sdl2.git
    - pytest -v -rP

  binaries_artifacts:
    path: "dist/*"


# Build macOS wheel
task:
  name: "Build macOS (x86_64) wheel"
  
  osx_instance:
    image: catalina-base

  install_script:
    - brew install python
    - python3 -m pip install -U wheel twine
    - python3 setup.py bdist_wheel

  script:
    - python3 -m pip install -U --force-reinstall --no-index --find-links=./dist pysdl2-dll
    - python3 -m pip install pytest git+https://github.com/marcusva/py-sdl2.git
    - pytest -v -rP

  binaries_artifacts:
    path: "dist/*"


# Build 32-bit x86 manylinux wheel
task:
  name: "Build manylinux2010 (i686) wheel"

  env:
    SDL2DLL_PLATFORM: manylinux2010

  container:
    image: quay.io/pypa/{$SDL2DLL_PLATFORM}_i686

  script:
    - linux32 ./manylinux.sh

  binaries_artifacts:
    path: "dist/*"


# Build 64-bit x86 manylinux wheel
task:
  name: "Build manylinux2010 (x86_64) wheel"

  env:
    SDL2DLL_PLATFORM: manylinux2010
  
  container:
    image: quay.io/pypa/{$SDL2DLL_PLATFORM}_x86_64

  script:
    - ./manylinux.sh

  binaries_artifacts:
    path: "dist/*"
