
# Build 32-bit x86 manylinux wheel
task:
  name: "Build manylinux2010 (i686) wheel"

  container:
    image: quay.io/pypa/manylinux2010_i686

  script:
    - linux32 ./manylinux.sh

  binaries_artifacts:
    path: "dist/*"


# Build 64-bit x86 manylinux wheel
task:
  name: "Build manylinux2010 (x86_64) wheel"
  
  container:
    image: quay.io/pypa/manylinux2010_x86_64

  script:
    - ./manylinux.sh

  binaries_artifacts:
    path: "dist/*"


# Build macOS wheel
task:
  name: "Build macOS (x86_64) wheel"
  
  osx_instance:
    image: catalina-base

  install_script:
    - brew install python
    - python -m pip install -U wheel twine
    - python setup.py bdist_wheel

  script:
    - python -m pip install -U --force-reinstall --no-index --find-links=./dist pysdl2-dll
    - python -m pip install pytest git+https://github.com/marcusva/py-sdl2.git
    - pytest -v -rP

  binaries_artifacts:
    path: "dist/*"
