matrix:
  include:
    - os: osx
      language: generic

install:
  - python setup.py bdist_wheel

script:
  - python -m pip install -U --force-reinstall --no-index --find-links=./dist sdl2dll
  - python -m pip install pytest git+https://github.com/a-hurst/py-sdl2.git@sdl2dll
  - pytest
