language: python

env:
  global:
    - TWINE_USERNAME=__token__ # password in Travis settings

matrix:
  include:
    - os: linux
      python: 3.8
      sudo: required
      install: python setup.py sdist # for source distribution
    - os: osx
      language: generic

before_install:
  - python -m pip install -U wheel twine

install:
  - python setup.py bdist_wheel

script:
  - python -m pip install -U --force-reinstall --no-index --find-links=./dist pysdl2-dll
  - python -m pip install pytest git+https://github.com/marcusva/py-sdl2.git
  - pytest

after_success: |
  if [[ $TRAVIS_TAG ]]; then
    if [ $(uname) = "Darwin" ]; then
      python -m twine upload --skip-existing dist/*.whl
    else
      python -m twine upload --skip-existing dist/*.tar.gz
    fi
  fi
