matrix:
  include:
    - os: osx
      language: generic

script:
  - python setup.py bdist_wheel
  - python -m pip install -U dist/*.whl
  - python -m pip install git+https://github.com/a-hurst/py-sdl2.git@sdl2dll
  - python test.py
