environment:
  TWINE_USERNAME: __token__ # password set in Appveyor settings
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install wheel twine"
  - "python setup.py bdist_wheel"

build: off

test_script:
  - "pip install --no-index --find-links=dist pysdl2-dll"
  - "pip install pytest git+https://github.com/marcusva/py-sdl2.git"
  - "pytest -v -rP"

on_success:
  - if [%APPVEYOR_REPO_TAG%]==[true] python -m twine upload --skip-existing dist/*.whl

artifacts:
  - path: dist\*
